### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by theusaf** [codingMASTER398/Kahootflood.weebly.com#6]
**Describe the bug**
The script crashes when joining using the name bypass.

**To Reproduce**
1. Enter pin
2. Say 'n' for antibot mode
3. Enter game pin
4. Enter a number of bots
5. Enter 'y' to use random names
6. Enter 'y' for name bypass
7. Enter 'y/n' for the rest of the settings
8. Crash.

**Expected behavior**
Bots join the game using the 'name bypass'

**Desktop (please complete the following information):**
 - Version 1.2.0

Error at line 161:35

**Comment by codingMASTER398** [comment]
This is a bug where the name sometimes becomes undefined for some unknown reason.
I will publish a fix for this ASAP
